# Generated by Django 4.2.1 on 2023-06-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kamar', models.CharField(max_length=30)),
                ('nama_kamar', models.CharField(max_length=10)),
                ('kapasitas', models.CharField(max_length=13)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_pelanggaran2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelanggaran', models.CharField(max_length=10)),
                ('nama_santri', models.CharField(max_length=30)),
                ('nama_kamar', models.CharField(max_length=30)),
                ('kategori', models.CharField(max_length=6)),
                ('tgl_kejadian', models.CharField(max_length=10)),
                ('keterangan', models.CharField(max_length=60)),
                ('hukuman', models.CharField(max_length=50)),
                ('nama_pengurus', models.CharField(max_length=30)),
                ('nomer_hp', models.CharField(max_length=13)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pendidikan', models.CharField(max_length=30)),
                ('nama_pendidikan', models.CharField(max_length=10)),
                ('kelas', models.CharField(max_length=13)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengurus', models.CharField(max_length=30)),
                ('staff', models.CharField(max_length=10)),
                ('no_telpon', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_santri2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_santri', models.CharField(max_length=8)),
                ('nama_santri', models.CharField(max_length=30)),
                ('nama_kamar', models.CharField(max_length=30)),
                ('tempat_tgl_lahir', models.CharField(max_length=35)),
                ('alamat', models.CharField(max_length=50)),
                ('pendidikan', models.CharField(max_length=1500)),
                ('nama_wali', models.CharField(max_length=30)),
                ('nomer_hp', models.CharField(max_length=13)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
