# Generated by Django 4.2.1 on 2023-06-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_guru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guru',
            options={'verbose_name_plural': 'Guru'},
        ),
    ]
