# Generated by Django 4.2.1 on 2023-07-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_model_kamar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(max_length=30)),
                ('staff', models.CharField(max_length=10)),
                ('no_telpon', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Model_guru',
            },
        ),
    ]
