# Generated by Django 4.1.5 on 2023-07-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_model_guru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_pengurus',
            old_name='password',
            new_name='Email',
        ),
    ]
