# Generated by Django 4.1.5 on 2023-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_delete_guru_remove_model_guru_no_telpon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_pendidikan',
            name='npsn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
