# Generated by Django 4.1.5 on 2023-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_model_pendidikan_npsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_santri2',
            name='nama_guru',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
