# Generated by Django 4.1.5 on 2023-08-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_model_santri2_nama_guru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_santri2',
            name='nama_guru',
        ),
    ]
