# Generated by Django 4.1.5 on 2023-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_model_santri2_nama_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_santri2',
            name='nomer_hp',
            field=models.CharField(max_length=15),
        ),
    ]
