# Generated by Django 4.1.5 on 2023-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_model_santri2_nomer_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_santri2',
            name='nomer_hp',
            field=models.CharField(max_length=13),
        ),
    ]
