# Generated by Django 4.1.5 on 2023-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_model_santri2_nomer_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_santri2',
            name='tempat_tgl_lahir',
        ),
        migrations.AddField(
            model_name='model_santri2',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='model_santri2',
            name='tgl_lahir',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='model_santri2',
            name='alamat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='model_santri2',
            name='id_santri',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='model_santri2',
            name='nama_kamar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='model_santri2',
            name='nama_santri',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='model_santri2',
            name='nama_wali',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='model_santri2',
            name='nomer_hp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='model_santri2',
            name='pendidikan',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
