# Generated by Django 4.1.5 on 2023-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_model_santri2_tempat_tgl_lahir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_guru',
            name='tempat_tgl_lahir',
        ),
        migrations.AddField(
            model_name='model_guru',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='model_guru',
            name='tgl_lahir',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
