# Generated by Django 4.1.5 on 2023-11-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_model_guru_tempat_tgl_lahir_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_guru',
        ),
    ]
